//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinsaitToDDL.Console.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MinsaitToDDL.Console.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///   &quot;TransDocType&quot;:1,
        ///   &quot;TransBehavior&quot;:1,
        ///   &quot;TransactionGuid&quot;:&quot;9C2DE3B6101F8347B8FB12B5B4234AE5&quot;,
        ///   &quot;TempTransIndex&quot;:0.0,
        ///   &quot;CreateDate&quot;:&quot;2025-10-13T00:00:00&quot;,
        ///   &quot;CreateTime&quot;:&quot;1899-12-30T12:49:40&quot;,
        ///   &quot;DeferredPaymentDate&quot;:&quot;2025-10-14T00:00:00&quot;,
        ///   &quot;ActualDeliveryDate&quot;:&quot;2025-10-13T00:00:00&quot;,
        ///   &quot;ContractReferenceNumber&quot;:&quot;8084103759&quot;,
        ///   &quot;DefaultWarehouse&quot;:2005,
        ///   &quot;PartyAddressID&quot;:0,
        ///   &quot;PartyAddressLine1&quot;:&quot;Morada nº 1 do Cliente nº 102021&quot;,
        ///   &quot;PartyAddressLine2&quot;:&quot;&quot;,
        ///   &quot;PartyPostalCod [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ddlSampleString {
            get {
                return ResourceManager.GetString("ddlSampleString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///   &quot;TransDocType&quot;:1,
        ///   &quot;TransBehavior&quot;:1,
        ///   &quot;TransactionGuid&quot;:&quot;B7B9913F92CA1543A72270FF00F261F6&quot;,
        ///   &quot;TempTransIndex&quot;:0.0,
        ///   &quot;CreateDate&quot;:&quot;2025-10-13T00:00:00&quot;,
        ///   &quot;CreateTime&quot;:&quot;1899-12-30T15:17:54&quot;,
        ///   &quot;DeferredPaymentDate&quot;:&quot;2025-10-14T00:00:00&quot;,
        ///   &quot;ActualDeliveryDate&quot;:&quot;2025-10-13T00:00:00&quot;,
        ///   &quot;ContractReferenceNumber&quot;:&quot;8084018270&quot;,
        ///   &quot;DefaultWarehouse&quot;:2005,
        ///   &quot;PartyAddressID&quot;:0,
        ///   &quot;PartyAddressLine1&quot;:&quot;Morada nº 1 do Cliente nº 102021&quot;,
        ///   &quot;PartyAddressLine2&quot;:&quot;&quot;,
        ///   &quot;PartyPostalCod [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string dllSampleString2 {
            get {
                return ResourceManager.GetString("dllSampleString2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;windows-1258&quot;?&gt;
        ///&lt;Invoice xsi:noNamespaceSchemaLocation=&quot;file:///D:/CLIENTES/$XSD_GENERICOS/FISI/InvoiceIeDocs.xsd&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        /// &lt;InvoiceHeader&gt;
        ///  &lt;InvoiceNumber&gt;NºDOCUMENTO&lt;/InvoiceNumber&gt;
        ///  &lt;TypeOfDocument&gt;380&lt;/TypeOfDocument&gt;
        ///  &lt;InvoiceType&gt;90&lt;/InvoiceType&gt;
        ///  &lt;ATCUD&gt;0-2401533&lt;/ATCUD&gt;
        ///  &lt;QRCODE&gt;QRCODE&lt;/QRCODE&gt;
        ///  &lt;InvoiceDate&gt;2022-04-11T00:00:00&lt;/InvoiceDate&gt;
        ///  &lt;InvoiceCurrency&gt;EUR&lt;/InvoiceCurrency&gt;
        ///  &lt;OtherInvoiceDates&gt;
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MinsaitInvoiceSample {
            get {
                return ResourceManager.GetString("MinsaitInvoiceSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] MinsaitInvoiveXsd {
            get {
                object obj = ResourceManager.GetObject("MinsaitInvoiveXsd", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;Order xsi:noNamespaceSchemaLocation=&quot;file:///C:/XSD_ALTOVA/FISI/OrderIeDocs.xsd&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        /// &lt;OrderHeader&gt;
        ///  &lt;OrderNumber&gt;NºENCOMENDA&lt;/OrderNumber&gt;
        ///  &lt;OrderDate&gt;2021-07-27T00:00:00&lt;/OrderDate&gt;
        ///  &lt;DocType&gt;220&lt;/DocType&gt;
        ///  &lt;OrderType&gt;9&lt;/OrderType&gt;
        ///  &lt;OtherOrderDates&gt;
        ///   &lt;DeliveryDate&gt;2021-07-30T11:00:00&lt;/DeliveryDate&gt;
        ///  &lt;/OtherOrderDates&gt;
        ///  &lt;BuyerInformation&gt;
        ///   &lt;EANCode&gt;GLN&lt;/EANCode&gt;
        ///  &lt;/BuyerInformation&gt;
        ///  &lt;Selle [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MinsaitOrderSample {
            get {
                return ResourceManager.GetString("MinsaitOrderSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;Order&gt;&lt;OrderHeader&gt;&lt;OrderNumber&gt;36685801&lt;/OrderNumber&gt;&lt;OrderDate&gt;2026-01-12T00:00:00&lt;/OrderDate&gt;&lt;DocType&gt;221&lt;/DocType&gt;&lt;OrderType&gt;9&lt;/OrderType&gt;&lt;OrderCurrency&gt;EUR&lt;/OrderCurrency&gt;&lt;OtherOrderDates&gt;&lt;DeliveryDate&gt;2026-01-16T00:00:00&lt;/DeliveryDate&gt;&lt;LastAcceptableDeliveryDate&gt;2026-01-16T00:00:00&lt;/LastAcceptableDeliveryDate&gt;&lt;/OtherOrderDates&gt;&lt;BuyerInformation&gt;&lt;EANCode&gt;5600000025963&lt;/EANCode&gt;&lt;InternalCode&gt;0142&lt;/InternalCode&gt;&lt;Department&gt;183&lt;/Department&gt;&lt;/BuyerInformation&gt;&lt;SellerI [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MinsaitOrderSampleReal {
            get {
                return ResourceManager.GetString("MinsaitOrderSampleReal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] OrderIeDocs {
            get {
                object obj = ResourceManager.GetObject("OrderIeDocs", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
